/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  defaultDocs: [
    { type: "doc", id: "intro"  },
    { type: "doc", id: "admin/index", label: "Admin docs"},    
    { type: "doc", id: "api/getting-started/index", label: "API docs"},    
  ],
  admin: [
    { type: "autogenerated", dirName: "admin" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "The api docs",
        slug: "/api"
      },
      items: require("./docs/api/sidebar.js")
    }
  ]
};

export default sidebars;