import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/getting-started/index",
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "api/post-api-auth-register",
          label: "Register a new user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-events-advent-status",
          label: "Get Advent Calendar Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-invoices-by-id-download",
          label: "Download an invoice PDF",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-server-by-id-disable-automatic-renewal",
          label: "Disable automatic renewal for a server",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-unban",
          label: "Unban a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-ban",
          label: "Ban a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-user-by-id-usage",
          label: "Get user resource usage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-api-user-delete",
          label: "Delete user account",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-api-auth-login",
          label: "Authenticate user with email and password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-coupon-by-code",
          label: "Get coupon details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-coins-leaderboard",
          label: "Get leaderboard",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-discount-by-discount",
          label: "Get discount details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-auth-pwreset-send",
          label: "Send a one-time reset password code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-coupon-by-code-claim",
          label: "Claim a coupon",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-earn-jfr-listing",
          label: "Fetch JFR listing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-earn-top",
          label: "Get leaderboard",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-earn-methods",
          label: "Get earning methods",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-earn-jfr-order",
          label: "Create a JFR activation invoice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-eggs-by-id",
          label: "Get egg by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-events-advent-days-by-day",
          label: "Check Advent Calendar Claim Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-eggs",
          label: "Get all eggs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-mobile-token-exchange",
          label: "postApiMobileToken-exchange",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-locations",
          label: "Get all locations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-invoices-by-id",
          label: "Get an invoice by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-locations-by-id-queues",
          label: "Get queue information by location ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-api-server-by-id-delete",
          label: "Delete a server",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-api-server-by-id-renew",
          label: "Renew a server",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-server-queue-by-id-delete",
          label: "Delete a queued server",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-api-shop-by-id",
          label: "Get shop item by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-api-server-by-id-edit-psp",
          label: "Edit server details",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/patch-api-server-by-id-edit",
          label: "Edit server resources",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/post-api-shop-resource-by-id-purchase",
          label: "postApiShopResourceByIdPurchase",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-shop-resource-listing",
          label: "Get Coin Shop Listing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-shop-listing",
          label: "Get shop listing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-server-queue-by-id",
          label: "Get server queue details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-server-by-id",
          label: "Get server details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-shop-plans-by-id-purchase",
          label: "Purchase a plan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-staff-by-collection-by-id-delete",
          label: "Delete a specific document from a collection",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-api-staff-by-collection-by-id-edit",
          label: "Edit a document in a collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-staff-conncheck-by-service",
          label: "Test service connection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-staff-by-collection-share-by-key",
          label: "Get shared collection data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-staff-by-collection-create",
          label: "Create a new field in a collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-staff-by-collection-list",
          label: "List items in a collection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-staff-queues-by-id-clear",
          label: "Clear server queue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-migration-rs",
          label: "Switch instance mode to Resources Splitting",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-server-create",
          label: "Create a new server",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-settings-edit",
          label: "Edit instance settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-settings-testemail",
          label: "Send a test email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-staff-delete-inactive-users",
          label: "deleteApiStaffDeleteInactiveUsers",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-api-staff-search-by-collection",
          label: "Search in a collection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-staff-migration-psp",
          label: "Migrate to per-server plans",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-staff-instance",
          label: "Get application settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-staff-advent-calendar-stats",
          label: "Get Advent Calendar Stats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-staff-disable-user-2-fa",
          label: "Disable a user's 2FA methods",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-add-coins",
          label: "Add coins to a user's account",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-reset-instance",
          label: "Reset instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-staff-transactions-share",
          label: "Get transaction statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-staff-force-loc-delete",
          label: "Force delete a location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-staff-update-loc-coin-renewal-rules",
          label: "Update location coin renewal rules",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-staff-get-alts-by-id",
          label: "Get possible alt accounts for a user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-by-id-servers",
          label: "Get user servers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-subscription-cancel",
          label: "Cancel a subscription",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-user-by-id-referrals",
          label: "Get user referrals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-by-id-info",
          label: "Get user information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-by-id-referrals-user-rules",
          label: "Get minimum referrals needed for custom link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-by-id-permissions",
          label: "Get user permissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-discord-by-did",
          label: "Fetch user by Discord ID",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-funds-history",
          label: "Get user transaction history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-by-id-invoices",
          label: "Get user invoices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-user-funds-topup",
          label: "Create a top-up invoice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-user-gamepanel-reset",
          label: "Reset game panel password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-user-passkeys-by-id-delete",
          label: "Delete a user's passkey",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/patch-api-user-passkeys-by-id-edit",
          label: "Edit a passkey",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-api-user-passkeys",
          label: "Get user passkeys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-user-referrals-top",
          label: "Get top referrals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-user-verify-by-code",
          label: "Verify user email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-user-referrals-edit-code",
          label: "Update referral code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-user-presence",
          label: "Update user presence",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-user-info",
          label: "Get user information (from token)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-user-verify-send",
          label: "Send verification email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-online",
          label: "Get online users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-api-user-password",
          label: "Change user password",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-api-sidebar-links",
          label: "Get the custom sidebar items defined by admins.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-api-user-profile",
          label: "Update user profile",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-api",
          label: "Get instance status, statistics & public frontend config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-articles",
          label: "Get articles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-auth-pwreset-by-code",
          label: "Reset password with a one-time code",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
